site_name: Auto Provision X
repo_name: garganshulgarg/auto-provision-x
repo_url: https://github.com/garganshulgarg/auto-provision-x
docs_dir: "docs"
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - awesome-pages
  - include-markdown
  - mermaid2
  # - literate-nav:
  #     nav-file: README.md
  #     implicit_index: true
  # - toc:
  #     toc_depth: 3
extra:
  version:
    provider: mike
