formatter: markdown table
sections:
  hide-all: true
  anchor: false 
sort:
  enabled: true
  by: required
settings:
  indent: 3
header-from: CLIENT_HEADER.md
content: |-

  {{ .Header }}
  
  {{ .Inputs }}

  {{ .Outputs }}

  
