name: Generate docs
on:
  - pull_request
jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
      timeout-minutes: 2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        submodules: 'true'
    - name: Generate client header documents.
      timeout-minutes: 4
      uses: terraform-docs/gh-actions@v1.0.0
      with:
       find-dir: modules/
       git-push: "true"
       config-file: ./docs/docs-auto-generate-configs/.client-header-terraform-docs.yml
       output-file: CLIENT_HEADER.md    
    - name: Generate client documents.
      timeout-minutes: 4
      uses: terraform-docs/gh-actions@v1.0.0
      with:
       find-dir: modules/
       git-push: "true"
       config-file: ./docs/docs-auto-generate-configs/.client-usage-terraform-docs.yml
       output-file: CLIENT_USAGE.md
