name: Sample Infra Deploy/Destroy

on: 
  workflow_dispatch:
    inputs:
      TERRAFORM_ACTION:
        type: choice
        description: 'Terraform Action'
        options:
          - apply
          - destroy
        default: 'apply'
        required: true

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  sample-infra-operators:
    runs-on: ubuntu-latest

    env:
      TF_COMMAND: "${{ github.event.inputs.TERRAFORM_ACTION }}"
      GCP_PROJECT_ID: "${{ secrets.GCP_PROJECT_ID }}"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # - name: Install Dependencies
      #   run: pip install -r ./scripts/requirements.txt

      - name: Checkout Code
        uses: actions/checkout@v2
      
      - id: 'google-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/${{ secrets.GCP_ACCOUNT_ID }}/locations/global/workloadIdentityPools/auto-provision-x-identity-pool/providers/auto-provision-x-oidc-provider'
          service_account: 'auto-provision-x@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/auto-provision-x-oidc-role
          role-duration-seconds: 600 # the ttl of the session, in seconds.
          aws-region: us-east-1
          
      - name: Deploy/Destroy Sample Infra
        run: python ./scripts/sample_infra_deploy.py $TF_COMMAND
