name: Sample Infra Deploy/Destroy
on: 
  workflow_dispatch:
    inputs:
      TERRAFORM_ACTION:
        type: choice
        description: 'Terraform Action'
        options:
          - apply
          - destroy
        default: 'apply'
        required: true

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  sample-infra-operators:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy/Destroy Sample Infra
        run: |
          cd ./samples
          terraform init
          terraform plan
      
