name: Test API Invocation

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -v https://4uas9wqkq1.execute-api.ap-northeast-1.amazonaws.com/dev
